### ISSUE TITLE
Exit button in nether is causing exception, function is working as expected. 

### ISSUE THREAD

**Issue by Centralan** [Centralan/Minigames#24]
**Server Error:**

2023-09-20 22:46:18 [SEVERE] [ItemControl] Exception caught: IllegalArgumentException: Cannot measure distance between mobarena and mobarena_nether
java.lang.IllegalArgumentException: Cannot measure distance between mobarena and mobarena_nether
        at org.bukkit.Location.distanceSquared(Location.java:456)
        at org.bukkit.Location.distance(Location.java:439)
        at no.runsafe.framework.internal.wrapper.BukkitLocation.distance(BukkitLocation.java:125)
        at no.runsafe.ItemControl.trading.TradingHandler.OnPlayerRightClick(TradingHandler.java:79)
        at no.runsafe.framework.internal.event.listener.player.RightClick.onEvent(RightClick.java:45)
        at no.runsafe.framework.internal.event.listener.player.RightClick.onEvent(RightClick.java:18)
        at no.runsafe.framework.internal.event.listener.EventRouterBase.invoke(EventRouterBase.java:65)
        at no.runsafe.framework.internal.event.listener.EventRouterBase.acceptEvent(EventRouterBase.java:33)
        at no.runsafe.framework.internal.event.listener.player.RightClick.acceptEvent(RightClick.java:38)
        at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463)
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759)
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.lang.Thread.run(Thread.java:750)
        
        
  **Lua code running that causes error:**

  function button_out_arena3(data)
        local player = Player:new(data.player);
          player:teleport(netherexit);
          NarenaPlayers[player.name] = nil;
          NplayerCount = NplayerCount - 1;
end

registerHook("INTERACT", "button_out_arena3", 143, "mobarena_nether", 1.0, 62.0, 5.0);

[Full script here](https://github.com/Centralan/PvE/blob/master/pve_nether.lua)

**Comment by Centralan** [comment]
Tests show it working on test server,will wait for live deployment
